{{- if .Values.ankrobes.enabled -}}
{{- $fullName := include "transcrobes.ankrobes.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.nginxingress.controller.ingressClass }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.transcrobes.ingress.tls.issuer }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ankrobes.ingress.maxBodySize }}
    nginx.ingress.kubernetes.io/upstream-hash-by: "$binary_remote_addr"
  name: {{ include "transcrobes.ankrobes.fullname" . }}
  labels:
    {{- include "transcrobes.ankrobes.labels" . | nindent 4 }}

spec:
{{- if .Values.transcrobes.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.transcrobes.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .Values.transcrobes.ingress.tls.secretName }}
{{- end }}
  rules:
  {{- range .Values.transcrobes.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /sync/
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          - path: /msync/
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          - path: /pod_name
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
