{{- if and .Values.transcrobes.enabled .Values.transcrobes.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transcrobes.transcrobes.fullname" . }}
  labels:
    {{- include "transcrobes.transcrobes.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.transcrobes.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.transcrobes.persistence.size }}
status: {}
{{- end }}
